name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@master
        with:
          github_user_name: vivekshahi918
          outputs: dist/snake.svg

      - name: Push the snake.svg to the output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b output
          mv dist/snake.svg github-contribution-grid-snake.svg
          git add github-contribution-grid-snake.svg
          git commit -m "Generate contribution snake"
          git push origin output --force
